name: CI/CD Flask App Deployment

on:
  push:
    branches:
      - staging
  release:
    types: [published]

jobs:
  deploy-to-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create .env file with MONGO_URI for tests
      run: echo "MONGO_URI=${{ secrets.MONGOURI }}" > .env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest test_app.py

    - name: Deploy to EC2 instance (Staging)
      env:
        EC2_PRIVATE_IP: ${{ secrets.EC2_PRIVATE_IP }}
        MONGO_URI: ${{ secrets.MONGOURI }}
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        echo "Deploying to Staging EC2 at $EC2_PRIVATE_IP"
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${EC2_PRIVATE_IP} << EOF
          sudo apt update -y
          sudo apt install -y python3 python3-venv python3-pip nginx git
          rm -rf Assignment_06_DevOps
          git clone https://github.com/JOYSTON-LEWIS/Assignment_06_DevOps.git
          cd Assignment_06_DevOps
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          echo "MONGO_URI=${MONGO_URI}" > .env
          pkill -f "python app.py" || true
          nohup python3 app.py > output.log 2>&1 &
          cat << 'NGINX_CONF' | sudo tee /etc/nginx/sites-available/flaskapp
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
              }
          }
          NGINX_CONF
          sudo ln -sf /etc/nginx/sites-available/flaskapp /etc/nginx/sites-enabled/flaskapp
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo nginx -t && sudo systemctl restart nginx
        EOF

        rm -f private_key.pem

  deploy-to-production:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create .env file with MONGO_URI for tests
      run: echo "MONGO_URI=${{ secrets.PROD_MONGO_URI }}" > .env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest test_app.py

    - name: Deploy to EC2 instance (Production)
      env:
        EC2_PRIVATE_IP: ${{ secrets.PROD_EC2_PRIVATE_IP }}
        MONGO_URI: ${{ secrets.PROD_MONGO_URI }}
        SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
      run: |
        echo "Deploying to Production EC2 at $EC2_PRIVATE_IP"
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${EC2_PRIVATE_IP} << EOF
          sudo apt update -y
          sudo apt install -y python3 python3-venv python3-pip nginx git
          rm -rf Assignment_06_DevOps
          git clone https://github.com/JOYSTON-LEWIS/Assignment_06_DevOps.git
          cd Assignment_06_DevOps
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          echo "MONGO_URI=${MONGO_URI}" > .env
          pkill -f "python app.py" || true
          nohup python3 app.py > output.log 2>&1 &
          cat << 'NGINX_CONF' | sudo tee /etc/nginx/sites-available/flaskapp
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
              }
          }
          NGINX_CONF
          sudo ln -sf /etc/nginx/sites-available/flaskapp /etc/nginx/sites-enabled/flaskapp
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo nginx -t && sudo systemctl restart nginx
        EOF

        rm -f private_key.pem
