name: CI/CD Flask App Deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Create .env for tests
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          export MONGO_URI=${{ secrets.MONGO_URI }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest test_app.py

      - name: Set up SSH and deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt update -y
            sudo apt install -y python3.11 python3.11-venv python3.11-dev git
            curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3.11
            rm -rf Assignment_06_DevOps
            git clone https://github.com/JOYSTON-LEWIS/Assignment_06_DevOps.git
            cd Assignment_06_DevOps
            python3.11 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            echo "MONGO_URI=${MONGO_URI}" > .env
            pkill -f "python app.py" || true
            nohup python app.py > output.log 2>&1 &
          EOF

      - name: Cleanup
        run: rm -f private_key.pem
